### ISSUE TITLE
[RFC] Co-autoria do módulo l10n_br_sale_stock

### ISSUE THREAD

**Issue by gabrielcardoso21** [OCA/l10n-brazil#1036]
Atualmente, grande parte do código do módulo l10n_br_sale_stock foi feito pelos desenvolvedores da Kmee. É justo que constemos como co-autores do módulo, não acham?

**Comment by rvalyi** [comment]
Hello @gabrielcardoso21 and @mileo .

Gabriel, it looks like you never touched the v8 or v10 localizations because had you done so, you would have seen that the l10n_br_sale_stock version you claimed was fixed was not functional at all compared to v8 or v10 (i'ts obvious when we are migrating our customers or simply on the when who were running v12 already). You claim you want to be the module maintainer, but in the next 2 months you did no new PR to fix the module. After your changes, had you a purchase order picking reception in your database and validating it would fail because you assume all stock.move had an link to a sale order. Come on you didn't even test you code in a real production database yet you claim to be the module maintainer  and co-author? A picking class was called SaleOrder https://github.com/OCA/l10n-brazil/commit/58a4b83aa305039e37b9729127e59ce2bd09763c#diff-806acdeb9347769cbf753fd7d7c37e9f77214589968044170c5d99fcf5d48c3a ??
What kind of code is that @gabrielcardoso21 ? Do you really think the rest of the OCA is like that???

At the end of the day, after fixing the code there is very little changes from you as I commented here:
https://github.com/OCA/l10n-brazil/pull/1103#issuecomment-786613384

All in all, we often welcome some of your contributrions @gabrielcardoso21 but I suggest to be have more humility when you start contributing to some 10 years old open source ERP project. If there were no old timers expert in the project and if these were not listen, I guarantee you nothing would work in the OCA.
I also encourage you to read about https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect
This is great to be young with a lot of ambition. But too much self confidence can also blind you.

@mileo You reviewed all of these commits from @gabrielcardoso21 so I suggest you think about it as well. I will soon show what kind of terrible consequences some beginner's code in the OCA (and any ERP in general) can have.

cc @marcelsavegnago

**Comment by gabrielcardoso21** [comment]
@rvalyi Well, thank you for the insults. I have no ambition to take personal credit. My request was to include our company in the authors section, since our contributions are Kmee contributions. Can you answer that objectively? I'm just an employee, man.
