### ISSUE TITLE
[BUG] Sale tax base incorrect when edit discount on sale.oder

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1159]
Hi,

@gabrielcardoso21  detect a error in one of your customers that when you change the discount on the sale.order model, the re-computation of the tax bases and tax values are not saved.

We are checking this issue in the next hours.

**Comment by gabrielcardoso21** [comment]
[12.0][REF] Update discount in button

When a sale order has more lines than the max allowed in the tree view (40 by default), the `discount_rate` only works once. We raised the limit of the number of lines shown in the sale order view, but some similar problems started ocurring when we changed the discount inside a line, saved and then changed the `discount_rate` in the sale order again. We finally changed the approach and put a button to do a manual onchange.

I was going to make a Pull Request, but since there's an issue, we can discuss it here. The alteration is in the branch 
https://github.com/kmee/l10n-brazil/tree/feature/update_discount_button.
