### ISSUE TITLE
[RFC] Release Police

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1207]
Hi Guys,

In the last two weeks i wrote a summary of the changes at l10n-brazil

https://github.com/kmee/l10n-brazil/releases/tag/v12-2021-11
https://github.com/kmee/l10n-brazil/releases/tag/v12-2021-10

I believe that the correct thing was to make this release through the OCA repository. 

The idea is to create a release every week, with tags and create a summary about the changes.

What do you think of the idea?

**Comment by rvalyi** [comment]
You wrote "#1206 Melhoria Adaptação da query para evitar a possibilidade de SQL Injection". That is not the reality, as I wrote in the PR there was no real SQL injection risk in this case, it was just to remove the pylint warning.

**Comment by marcelsavegnago** [comment]
acho que ficou um errinho aqui

OCA#1186 Bug: Erro ao tentar criar um documento relacionado sem CNPJ, **o sistema sem tentava** validar o campo CNPJ.

**Comment by mileo** [comment]
Texto corrigido, vlw.

**Comment by mileo** [comment]
@rvalyi e @marcelsavegnago What do you think of the idea?

**Comment by rvalyi** [comment]
I think very few people that are not part of the repo contributor customer base will make it for the v12->v13/v14 migration because of the account.move -> account.invoice migration in the core of Odoo account module. In OCA/l10n-brazil it will be quite trivial, but just to run and debug OpenUpgrade and their customization most of curious people will just fail. So I feel this kind of shiny backlog is passing them a false sense of security that is not real and will encourage them to fail instead of doing the real work (or paying for it) to get things working if they cannot even read a repo git log...

Instead I think on v14 things may be stabilized enough to think about such a thing. But the point is we should clear out a few key PRs on v12 before going v14 or things will diverge in a suicidal way.

Especially no other OCA repo does such a repo backlog because the release policy is not a repo thing, but is instead distributed module by module, author by author, this is the way the OCA works, like it or not. Given the work in the current repo modules is done may be 70% by Akretion, should there be any global repo release policy thing that would need to be managed by Renato and not you... Sorry but I have never seen such a thing were a minor contributor who just screwed a bunch of people in a failed fork due to a totally broken design then comes back into the original project and tries to fake a project release policy alone in a project he has no control over. In fact, experienced people may even doubts what is the real intention behind all these fireworks, let's say we have an idea...

**Comment by mileo** [comment]
> I think very few people that are not part of the repo contributor customer base will make it for the v12->v13/v14 migration because of the account.move -> account.invoice migration in the core of Odoo account module. In OCA/l10n-brazil it will be quite trivial, but just to run and debug OpenUpgrade and their customization most of curious people will just fail. So I feel this kind of shiny backlog is passing them a false sense of security that is not real and will encourage them to fail instead of doing the real work (or paying for it) to get things working if they cannot even read a repo git log...
> 
> Instead I think on v14 things may be stabilized enough to think about such a thing. But the point is we should clear out a few key PRs on v12 before going v14 or things will diverge in a suicidal way.
> 
> Especially no other OCA repo does such a repo backlog because the release policy is not a repo thing, but is instead distributed module by module, author by author, this is the way the OCA works, like it or not. Given the work in the current repo modules is done may be 70% by Akretion, should there be any global repo release policy thing that would need to be managed by Renato and not you... Sorry but I have never seen such a thing were a minor contributor who just screwed a bunch of people in a failed fork due to a totally broken design then comes back into the original project and tries to fake a project release policy alone in a project he has no control over. In fact, experienced people may even doubts what is the real intention behind all these fireworks, let's say we have an idea...

In my opinion the main objective of a weekly release policy with a report of the changes is to improve the communication of what is being done and to bring in new contributors.

Whether they are internal to our own companies or the community.

This brings two important benefits in two aspects:

For the internal team:

1. Reduces the need for internal alignment between the team regarding OCA's news;
2. It makes possible a retrospective of what was done weekly.
3. Helps track client versions on a weekly basis and helps detect regressions.

For the community, the above items are also applicable, but in addition we have:

1. It increases the understanding of what is done, through clearer communication, which is not always possible through pull requestes.
2. It generates contribution interest and opens the dialogue for that.
3. It also allows them to version control in a simpler way, creating simple checkpoints to allow them to test the system.

For example:

![image](https://user-images.githubusercontent.com/1975978/111286836-62872980-8621-11eb-870a-30abb01a69e6.png)

The community can track the changes and avoid questions like this.

----------------

If your company doesn’t want to encourage contributions, no problem, I don’t care to keep this weekly policy alone.

However alone it can be easier to find errors like those mentioned in the message above (SQL and CNPJ), doing a joint work would be easier.
