### ISSUE TITLE
[Q&A] What are the cases where an author, person or company,  can be removed in the modules ?

### ISSUE THREAD

**Issue by mbcosta** [OCA/l10n-brazil#1252]
Hi PSCs @renatonlima @rvalyi @mileo 

Please I like to undestand what are the cases an author, person or company, can be removed in the modules ? My doubt emerge because I saw some removes happening in some files and don't understand the reason, see:

* Remove company, module l10n_br_delivery replaced Akretion as author to KMEE during migration

![image](https://user-images.githubusercontent.com/6341149/112532080-26716880-8d87-11eb-8566-78363c54a8d6.png)

https://github.com/OCA/l10n-brazil/commit/1f628f9811be400cb1e4fb5dbd31164d4c1c25f3#diff-a39720c01663b56506c1c9972ab452c8154bc6a85bc5341f2a2fcf2f9a26ae2b

* Remove author, PR https://github.com/OCA/l10n-brazil/pull/1125 module l10n_br_fiscal

![image](https://user-images.githubusercontent.com/6341149/112532756-f4acd180-8d87-11eb-8d6a-12dd53c36582.png)

If there are changes I think the right should be included another author but not remove, or am I wrong ? Are there any justification ?

I think after created file or module we can just included other authors but not remove, and it should be done by general rule to avoid conflicts and make it clear to developers, my sugesstion are use the percent of 25% of changes to become an author at file and 50% at module. What do you think about ?

**Comment by rvalyi** [comment]
sadly not the 1st time. Same company, same behavior, less agressive the other day, but just as shocking
https://github.com/OCA/l10n-brazil/issues/1036

In the meantime, this company has dozens of stalled PRs with modules that never **won't even install, have not a single test:**
https://github.com/OCA/l10n-brazil/pull/1156
https://github.com/OCA/l10n-brazil/pull/852
https://github.com/OCA/l10n-brazil/pull/868
https://github.com/OCA/l10n-brazil/pull/869
https://github.com/OCA/l10n-brazil/pull/870
https://github.com/OCA/l10n-brazil/pull/871
https://github.com/OCA/l10n-brazil/pull/850
https://github.com/OCA/l10n-brazil/pull/854
to mention just a few ones... What I sometimes call make "fireworks in the project". All these "help wanted" tags never attracted any contributions to these PRs of course, just fireworks and fireworks to produce some illusion with some noob audience sadly.

things with **very low quality** that loose anyone trying to actually contribute to the project but instead of making these things actually work with an OCA quality, @mileo, not satisfied with bringing a lots of companies **NOWHERE** behind a failed fork with zero quality a few years ago now sems more worried to steal our own work and make it looks it's from his company KMEE. BTW, in 2017 we even took weeks to explain @mileo how bad the design was and how much all that would just fail, all registered in the OCA PRs here https://github.com/OCA/l10n-brazil/pull/529) and still he went this way and failed hard just as we predicted. A sort of #euavisei of the project for Brazilian people. And still after all this, @mileo wants to give us lessons it seems with new PR's with such broken designs that would have killed the project again if we let them happen:
https://github.com/OCA/l10n-brazil/pull/806
https://github.com/OCA/l10n-brazil/pull/820
This sucks! I can not think about any OCA repo where such **trolling behavior** is tolerated. Please @mileo change your whole attitude in the project or we would be forced to take the necessary actions. This is not so much of the technical problem, this is much more an attitude problem, a recurring one sadly.

cc @gabrielcardoso21 May be you understand better why I was pissed of the other day in https://github.com/OCA/l10n-brazil/issues/1036 because sadly this is not the 1st time, far from it in fact. I critiziced firmly what you did, but there is no personal insult however unlike what you suggested.

**Comment by rvalyi** [comment]
cc @marcos-mendez as you have been elected an OCA delegate as well and you also live in Brazil, it's good if you can track these issues down to the very registered facts instead of letting you be fooled by some superficial speech. Thanks.

**Comment by mileo** [comment]
> Hi PSCs @renatonlima @rvalyi @mileo
> 
> Please I like to undestand what are the cases an author, person or company, can be removed in the modules ? My doubt emerge because I saw some removes happening in some files and don't understand the reason, see:
> 
> * Remove company, module l10n_br_delivery replaced Akretion as author to KMEE during migration
> 
> ![image](https://user-images.githubusercontent.com/6341149/112532080-26716880-8d87-11eb-8566-78363c54a8d6.png)

Hi @mbcosta 

You can see more about it at the migration PR https://github.com/OCA/l10n-brazil/pull/967

In the end of the pull request I commented:

https://github.com/OCA/l10n-brazil/pull/967#issuecomment-744357549

![image](https://user-images.githubusercontent.com/1975978/114597862-a3e21780-9c67-11eb-80d6-24c9f4d133bb.png)

And the discussion was not resumed until the opening of this issue. And we will be happy to correct any injustice.

Could you create a pull request adding Akretion as a CO-Author?

> 
> [1f628f9#diff-a39720c01663b56506c1c9972ab452c8154bc6a85bc5341f2a2fcf2f9a26ae2b](https://github.com/OCA/l10n-brazil/commit/1f628f9811be400cb1e4fb5dbd31164d4c1c25f3#diff-a39720c01663b56506c1c9972ab452c8154bc6a85bc5341f2a2fcf2f9a26ae2b)
> 
> * Remove author, PR #1125 module l10n_br_fiscal
> 
> ![image](https://user-images.githubusercontent.com/6341149/112532756-f4acd180-8d87-11eb-8d6a-12dd53c36582.png)
> 
> If there are changes I think the right should be included another author but not remove, or am I wrong ? Are there any justification ?
> 

From what I interpreted this is a model that has been completely rewritten and only one field has been maintained, as the PR is still pending review (since Apr 2020 https://github.com/OCA/l10n-brazil/pull/820).

We are still waiting for the review by the Akretion team, we will be happy to fix any issue.

**Comment by mbcosta** [comment]
Hi @mileo 

"You can see more about it at the migration PR #967

In the end of the pull request I commented:

And the discussion was not resumed until the opening of this issue. And we will be happy to correct any injustice.
"

Someone work for you made the change, you wrote this is wrong and should be fix, it's a simple commit, after four months nothing was did, why ?

"Could you create a pull request adding Akretion as a CO-Author?" 

I needed to implement some refactorings in l10n_br_delivery in PR https://github.com/OCA/l10n-brazil/pull/1301 at the branch used @renatonlima made change of Author in module here https://github.com/OCA/l10n-brazil/pull/1301/commits/ae84fa30ca2cd68b35f476092725dabc6431b6ab, I think you Luis Mileo and Renato Lima should talk and achive an agreement about it.

"From what I interpreted this is a model that has been completely rewritten and only one field has been maintained, as the PR is still pending review (since Apr 2020 #820)."

The same argument if applied to file can be used for a module, it's seems this idea was used for l10n_br_delivery. If the other PSCs belive it's right and should applied as general rule for the repository, please I ask you PSCs to make it clear, I have worked in PR https://github.com/OCA/l10n-brazil/pull/768 where some files was rewritten, so in those cases the License Header of company or person should be removed ?

**Comment by renatonlima** [comment]
> And the discussion was not resumed until the opening of this issue. And we will be happy to correct any injustice.

@mileo,

This is not right, l10n_br_deliery module is a module that exists in OCA since version 6.1, this is not a new module.

It doesn't make sense for you to migrate a module there and remove the module's authorship and copyrights to after we create one PR to add these that shouldn't removed in module migration.

**Comment by rvalyi** [comment]
fixed in #1301
