### ISSUE TITLE
[RFC][10.0][12.0] Melhorias na estrutura dos módulos de Cobrança e CNAB

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#696]
Durante a migração dos módulos de geração de boletos e arquivo CNAB, eu analisei os módulos que fazem parte da dependência para emissão dos boletos e CNABs e tinha alguns erros de dependências, na verdade algumas dependências eram baseadas nas dependências dos módulos da 8.0 que mudaram na v10.0, eu desenhei um gráfico de com o design da estrutura dos módulos de boletos e CNABs:

![image](https://user-images.githubusercontent.com/211005/58110963-e52a3380-7bc6-11e9-9738-ca7051d89d22.png)

* **l10n_br_account_payment_order**: Módulo base para as ordens de cobrança e ordens de pagamentos, depende do l10n_br_account, account_payment_order

* **l10n_br_account_payment_cobranca**: Módulo base para a ordem de cobrança é a base para implantação do CNAB e Boletos, agora este módulo é a base tanto para a emissão dos boletos quanto para a geração do arquivo CNAB, antes era separado (boleto e CNAB) porque poderia gerar um boleto sem registro que neste caso não havia a necessidade gerar o arquivo CNAB e enviar para o banco, mas com o fim dos boletos sem registro, não há motivo para manter os dois módulos separados.

* **boleto_brcobranca**: Módulo para emissão de boletos utilizando a biblioteca BrCobrança via API https://github.com/akretion/boleto_cnab_api

* **cnab_brcobranca**: Módulo para gerar arquivos CNAB de cobrança utilizando a biblioteca BrCobrança via API https://github.com/akretion/boleto_cnab_api

* **boleto_pyboleto**: Módulo para emissão de boletos utilizando a biblioteca BrCobrança PyBoleto

* **cnab_pycnab**: Módulo para gerar arquivos CNAB de cobrança utilizando a biblioteca PyCNAB

* **l10n_br_account_payment_pagamento**: Módulo base para a ordem de pagamentos é a base para implantação do CNAB para o registro de pagamentos, transferencias e folha de pagamento utilizando o layout CNAB para pagamentos.

* **pagamento_pycnab**: Módulo para gerar arquivos CNAB de pagamento utilizando a biblioteca PyCNAB

Estou registrando este Issue para discutir as mudanças propostas e referencias os PRs tanto de migração quanto de refactoting.

**Comment by renatonlima** [comment]
Migração do módulo l10n_br_bank_payment #680
Migração do módulo l10n_br_account_payment_mode #684
Refatoramento do módulo l10n_br_bank_payment para l10n_br_account_payment_order e merge deste módulo com o l10n_br_account_payment_mode #695

**Comment by mileo** [comment]
Última versão do manual do cnab: https://cmsportal.febraban.org.br/Arquivos/documentos/PDF/Layout%20padrao%20CNAB240%20%20V%2010%2005%20-%2005_11_18.pdf

**Comment by mileo** [comment]
Pessoal algumas considerações:
@renatonlima @mbcosta @lfdivino @hendrixcosta @rvalyi @sadamo 

Recentemente fizemos alguns refactorys no codigo do l10n_br_account_payment_cobranca e avançamos bastante em diversas features, mas ainda estamos desenvolvendo. Vocês podem acompanhar o trabalho no PR #700. Estamos quase finalizando as melhorias, mas ainda existem alguns problemas que vou enumerar abaixo:

- [ ] Realizar a baixa automática através do arquivo de retorno;
- [ ] Criar o campo meio de pagamento (Boleto, Cheque, cartão de crédito e etc) no account.payment.term;

01 = Dinheiro 
02 = Cheque 
03 = Cartão de Crédito
04 = Cartão de Débito 
05 = Crédito Loja 
10 = Vale Alimentação 
11 = Vale Refeição 
12 = Vale Presente 
13 = Vale Combustível 
15 = Boleto Bancário 
90 = Sem pagamento (apenas para NFe)
99 = Outros

- [ ] Refatorar o  account.payment.mode para representar os diversos tipos de carteiras de cobrança(uma empresa pode ter vários tipos de carteiras, cada um com um valor negociado, taxa de registro de boleto e etc) e alem disso  ted/doc/salário e etc;

Nossa previsão é que acabarmos no máximo na semana que vem e na sequência migraremos os módulos para a v12.

OBS: @mbcosta sugiro que você aguarde mais alguns dias para continuar trabalhando neste PR: https://github.com/OCA/l10n-brazil/pull/702

**Comment by mbcosta** [comment]
ola @mileo 
Essse PR que vocês estão trabalhando já possui a extração do repositório https://github.com/odoo-brazil/odoo-brazil-banking do modulo l10n_br_account_payment_banking_cnab , a migração tanto desse modulo quanto do l10n_br_account_payment_boleto e a unificação desses dois modulos no l10n_br_account_payment_cobranca , na minha opinião esse PR deveria se restringir a isso, porque incluir alterações e aumentar o escopo do modulo durante a migração torna a revisão maior do que deveria aumentando a possibilidade do código ter problemas, já que algo novo que não era feito antes está sendo implementado em uma nova versão, e como já foi falado e escrito a idéia da migração entre a 8 -> 10 seria de fazer apenas a migração do código, e novas implementações seriam feitas na versão 12, quer dizer porque fazer alterações em uma versão que pretendemos usar apenas para ser intermediaria na migração de dados entre a 8 e 12 ? Sobre o que se pretendem refatorar/implementar : 

" Realizar a baixa automática através do arquivo de retorno;"
Como escrevi acima o ideal é que novas implementações sejam feitas em PR separados e de forma mais isolada possível, para que em cada PR tenha apenas algo especifico que pode ser debatido naquele PR e não misturado com diversas outras alterações, porque dessa forma se diminui as possibilidades de erros. Nesse caso especifico eu realmente sugiro que isso seja feito na versão 12, até onde vi realizar conciliação automática do arquivo CNAB recebido possui um problema que talvez seja maior no caso do Brasil que é os valores que estão no programa ( as NFe que geraram os Boletos ) podem divergir dos valores que vem no arquivo CNAB basicamente por motivos de Desconto, Abatimento, Juros e etc ( aqui seria importante saber quantas possibilidades de divergências temos ), para automatizar isso seria preciso incluir no programa algo como "Fazer isso se o valor for maior" ou "Fazer aquilo se o valor é menor" mas será que somente esses dois parâmetros atendem ? Quem fica responsável por resolver essa divergência o programa/codigo ou o operador/usuario ? Ou como vocês pretendem resolver essa questão ?

"Criar o campo meio de pagamento (Boleto, Cheque, cartão de crédito e etc) no account.payment.term;"
Mesmo caso, o ideal seria ser feito na versão 12 em um PR isolado. Acredito que aqui se trata da questão da NFe 4.0 que permite que cada parcela de pagamento tenha um Modo de Pagamento, pelo que entendi vocês pretendem criar um campo do tipo "Select" com essa lista dento do account.payment.term, vejo um problema que é o seguinte hoje no objeto account.invoice nos temos o campo account.payment.mode ( Modo de Pagamento ex.: Boleto, Cartão, Dinheiro ) e o account.payment.term ( Forma de Pagamento ex.: 30/60/90, 15/30/45 ), dependendo de como for implementado podemos ter inconsistências de dados já que podemos ter uma NFe ( objeto account.invoice ) com um Modo de Pagamento = "Boleto" e a Forma de Pagamento = "30/60/90 01 = Dinheiro " ( o novo campo que vocês pretendem criar ) isso acabaria se tornando uma inconsistência porque qual seria o real Modo de Pagamento ? Qual campo é confiável ? Modo de Pagamento ou a Forma de Pagamento ?   

"Refatorar o account.payment.mode para representar os diversos tipos de carteiras de cobrança(uma empresa pode ter vários tipos de carteiras, cada um com um valor negociado, taxa de registro de boleto e etc) e alem disso ted/doc/salário e etc;"
Mesmo caso, o ideal seria ser feito na versão 12 em um PR isolado, sinceramente não vejo sentido em implementar novas funcionalidades em uma versão intermediaria ( 10.0 ), existem mudanças em objetos e funcionalidades entre as versões, se queremos usar a 12 porque gastar tempo incluindo funcionalidades que vão precisar ser revistas logo em seguida em um curto espaço de tempo ? O que isso acrescenta ? Porque não fazer na última versão que é aquela que pretendemos trabalhar ?

**Comment by mileo** [comment]
@mbcosta 

"Realizar a baixa automática através do arquivo de retorno;" 

Diria que é uma das maiores fontes de prejuízos relacionadas ao CNAB. Pergunte a um cliente de vocês, se eles já tiveram ou conhecem algum empresário que já teve prejuízo com algum colaborador que acidentalmente ou propositalmente de baixa em algum boleto. Esta é a forma de fechar o fluxo e também facilita na implantação e auditoria posterior.

"Criar o campo meio de pagamento (Boleto, Cheque, cartão de crédito e etc) no account.payment.term;"
"Refatorar o account.payment.mode para representar os diversos tipos de carteiras de cobrança(uma empresa pode ter vários tipos de carteiras, cada um com um valor negociado, taxa de registro de boleto e etc) e alem disso ted/doc/salário e etc;"

Se trata da forma correta de se modelar as formas de pagamento. 

"Porque não fazer na última versão que é aquela que pretendemos trabalhar?"

Pois a os módulos da OCA estão na v10 e o projeto que esta bancando esta refatoração esta sendo desenvolvido na v10.

Podemos posteriormente, com recursos de P&D, atuar na migração para v12. Entretanto isso só deve ser feito quanto a definição do uso dos módulos financeiros seja tomada. O que mudaria um pouco o roadmap dos módulos. 

Alem disso utilizando o modelo de dados atual em produção foi possível validar diversas inconsistências que não foram detectadas na atual arquitetura, por conta disso o sprint com novas features. Não adianta nada um código nos "padrões OCA", com 100% de coverage de testes viciados e  erros que impedem o uso ou podem causar prejuízos aos usuários.

**Comment by mbcosta** [comment]
ola @mileo 

"Pergunte a um cliente de vocês, se eles já tiveram ou conhecem algum empresário que já teve prejuízo com algum colaborador que acidentalmente ou propositalmente de baixa em algum boleto"

Existe algum programa que tem interação humana que não tem problema com erros de digitação por falta de atenção do operador/usuário ? De quem é a responsabilidade do desenvolvedor ou do usuário que normalmente é um funcionário da empresa, recebe por seu trabalho tem responsabilidades e usa o programa como ferramenta ? Você também colocou a hipótese de "propositalmente" , temos o LOG de acessos e fora isso como um desenvolvedor pode resolver o problema de funcionários mal intencionados ? E nesse caso um projeto de código aberto que alguém sem nenhum vínculo comercial conosco pode baixar, instalar e usar como vamos nos responsabilizar por uma implementação feita por alguém que desconhecemos ? Entendo que o programa sempre que possível tente otimizar e automatizar os processos mas a questão principal que perguntei é como serão tratadas as divergências entre valores do que está no programa com o que vem no arquivo CNAB ? Existem Juros, Abatimento e Descontos que podem ser feitos ou ocorrem depois do Boleto já impresso e enviado para o cliente, como fica isso ? Ou na forma que vocês estruturaram não existe esse problema ?

"Se trata da forma correta de se modelar as formas de pagamento."

Baseado em que ? Desculpe mas pelo que li a forma de implementação está errada basicamente porque será preciso criar a mesma Condição de Pagamento para cada Forma de Pagamento, exemplo 30/60/90 Dinheiro, 30/60/90 Boleto , 30/60/90 Cheque , 30/60/90 Cartão de Credito; é isso mesmo ? Se for assim, será que essa é melhor forma de implementar ?

"Não adianta nada um código nos "padrões OCA", com 100% de coverage de testes viciados e erros que impedem o uso ou podem causar prejuízos aos usuários."

Bom estamos em um repositório da OCA e você é um PSC 

https://odoo-community.org/page/oca-project-steering-committee-guide ,
What is the PSC responsible for ?
- Enforcing its contributors to follow the OCA Conventions

 Sua pergunta seria porque um repositório da OCA deveria ter padrões de qualidade da OCA ? Minha opinião é que todos projetos de código aberto de sucesso só chegaram a isso porque a qualidade do código era muito superior ao que é feito em código fechado, isso só é possível justamente por ser aberto e por ter a interação de diversas pessoas o que acaba tendo por consequência uma padronização no código no sentido de adotar as melhores práticas possíveis no caso do odoo abstração, heranças, api, PEP8, codigo pythonico e etc essas práticas e recomendações acabam gerando um código melhor no longo prazo, beneficiando a todos os envolvidos.

"100% de coverage de testes viciados" 
Quais são os testes "viciados" ? Fiz o melhor que pude, em todos os PRs existia a possibilidade de se fazer revisão e apontar aquilo que você não concorda ou que deveria estar melhor feito, agradeço se puder fazer e enviar testes melhores, porém com os testes( mesmo com problemas) permitem refatorar o código com menores chances de causar algum erro

" erros que impedem o uso ou podem causar prejuízos aos usuários."

 Quais erros ? Tem "issues" abertos ? Cara sobre "causar prejuízos aos usuários" com todo o respeito existe algo bastante especifico sobre isso na própria licença em que o programa é disponibilizado

http://www.gnu.org/licenses/agpl-3.0.html

Disclaimer of Warranty.
THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

Acredito que existe uma certa confusão e mistura de dois ambientes no que você está escrevendo sobre o código que deve ser desenvolvido. Um é o do seu cliente onde você e sua empresa tem responsabilidades legais, contratuais, de prazos, de suporte e etc e o outro é o do repositório da OCA/Comunidade onde a questão principal é o código em si, como foi feito, implementado, PEP8, testes e etc. O seu cliente ( na maioria dos casos ) não vai se importar em como foi implementado o código nem se você segue ou não os padrões de qualidade da OCA, talvez eles nem saibam do que se trata, apenas se aquilo que ele especificou ou precisa está funcionando, porém aqui nós não somos clientes e sim outros desenvolvedores que vão trabalhar com esse mesmo código e vão se responsabilizar perante os próprios clientes assim como vocês, é o nosso "ganha-pão", por isso é preciso justificar alterações/implementações/melhorias com argumentos técnicos dizer que "o cliente quer isso aquilo e aquilo outro e tem que ser assim por causa disso" isso pode servir dentro do ambiente privado de empresas mas e dentro da OCA, a opinião dos desenvolvedores tem que se sujeitar sem críticas ao que um suposto cliente quer ou o que um desenvolvedor decide unilateralmente sem nem precisar justificar o que está sendo feito ? Porque então participar da OCA ou mesmo fazer código aberto, se não há interesse em discutir implementações ? Quem vai ser o responsável real por uma implementação o desenvolvedor/empresa ou o cliente ? Algum cliente vai acordar de madrugada para dar suporte ou corrigir uma implementação mal feita ? Quem decide o escopo do projeto dentro da OCA os desenvolvedores ou os clientes ? Espero que essas questões ajudem a esclarecer o debate e que as críticas sejam vistas como construtivas para termos um código melhor para todos.

**Comment by mileo** [comment]
Não gosto muito de fugir da discussão ou escrever demasiadamente. Mas vou precisar entrar em detalhes para expor melhor minha opinião:

Como PSC da localização tenho responsabilidade indireta por qualquer resultado indesejado que algum utilizador tiver ao usar o Odoo. Apesar da licença assegurar que quem utiliza o programa, o está usando por sua conta em risco.

Enumero os utilizadores para deixar bem claro:

- Clientes da KMEE, seus funcionários e suas famílias;
- Não clientes da KMEE, clientes de outras empresas, seus funcionários e suas famílias, futuros consultores/desenvolvedores que estão tentando prestar serviços com Odoo;
- Rupturas: Empresas/Pessoas que testaram o Odoo e não gostaram;

Então caso ocorra alguma falha no software que prejudique algum desses utilizadores de forma indireta ou direta nós, da KMEE, nos sentimos responsáveis, e isso pode acontecer de diversas formas:
 - Não adotamos uma trava de segurança, mitigamos todos os riscos;
 - Não revisamos um pull request com calma;
 - Decidimos evitar uma discussão devido a burocracia;
 - Não fomos cuidadosos na explicação de uma RFQ ou ao revisar um PR;

Sobre os padrões de qualidade, não são definidos pelo que a gente prega (todas as regras da OCA), mas sim o que toleramos. Não vejo por que aceitar um PR na v10, somente para facilitar a migração, quais seriam as consequências disso? O código do projeto Odoo Brasil não deve entrar na OCA se estiver ruim.

Devemos manter as mesmas funcionalidades e implementar testes para testar algo que não garante todos os requisitos?

Qual é minha missão como PSC de uma localização? Tratar apenas das responsabilidades descritas no manual? Na minha opinião vai muito além disso, é se tornar responsável por tudo que impacta o sucesso da localização:
- Dependências;
- Fóruns/Grupos/;
- Resolução de conflitos entre membros;
- Divulgação;
- Produção de eventos;
- etc;
- e por fim o código;

A intenção dessas features são resolver os problemas, melhorar as funcionalidades. Otimizando os recursos dos clientes e nossos. Fazer o que precisa ser feito para os boletos funcionarem corretamente:

O modo de pagamento, Boleto em especial, pode estar relacionado a várias carteira de cobrança, que representa os diversos produtos ofertados pelo banco e cada conta corrente pode ter várias carteiras, por exemplo:
- Uma carteira para cada departamento ou tipo de serviço da empresa;
- Carteira para cobranças espontâneas: Boletos do GAAC / Associações (imagina só o GAAC pagar uma taxa de 5 reais para cada boleto emitido, mesmo sem saber se o cliente irá pagar, então nesse caso o banco só cobra quando o cliente paga);
- Carteira para carne (sei que ela existe, mas não sei explicar a diferença);
- Uma carteira a ser enviada pela Empresa, uma pelo banco e outra pelos correios;

Referente o porque a forma de pagamento deve ser atrelada ao modo de pagamento seguem alguns motivos:
1. Condições comerciais: https://docs.google.com/document/d/1Vc_iUcddLPU9odkXwVJ-DdPKH4KKslxUe5_lKuqaKZs/edit
2. Questões legais/fiscais; (Basta verificar o manual da NF-E 4.0 e o SPED Fiscal) Temos que garantir a integridade da informação da NOTA e sua posterior consistência fiscal;
3. Usabilidade:
      - Usuário só pode ter acesso a determinadas condições comerciais;
      - O usuário seleciona o campo parcelamento em 12x e quando ele vai selecionar o modo de pagamento boleto, o pagamento em boleto em 12x não é permitido;

É muito mais simples assegurar três os itens acima com apenas um modelo; 

Além disso atento a facilidade da carteira de cobrança ser representada pelo modelo account.payment.order https://github.com/kmee/l10n-brazil/blob/extraction/l10n_br_banking_cnab/l10n_br_account_payment_cobranca/models/account_payment_mode.py#L18 pois:
    - Ele não é obrigatório, na venda / nem na compra / nem na fatura. Permitindo ao faturista selecionar a melhor carteira de cobrança para a ocasião da fatura;
    - Já está devidamente acoplado ao account.payment.order e representa todos os detalhes citados;

Referente ao apontamento do Juros/Taxas e etc. Na daily de hoje do nosso time que, verificamos que a melhor forma de implementar isso é criar campos account.account na carteira de cobrança para separar esses lançamentos e trabalha-los no processamento do arquivo: https://github.com/kmee/l10n-brazil/blob/extraction/l10n_br_banking_cnab/l10n_br_account_payment_cobranca/models/l10n_br_cnab.py#L678-L734 e iremos trabalhar nisso nos próximos dias.

Referente ao pagamento de boletos, existem as formas:

1. Quitação: Quando o cliente paga o título na rede bancária;
2. Baixa de pagamento: Quando o cliente ou a empresa afirma que a dívida não existe mais. Isso pode ocorrer pelos seguintes motivos:
     - A cobrança foi feita indevidamente;
     - O cliente pagou de outra forma;
    - Ou por alguma condição comercial a cobrança foi suspensa;

O processo de baixa abre uma brecha de erros e/ou fraudes com relação ao pagamento caso a empresa não controle corretamente o saldo de todos os seus caixas e contas corretamente. Então a melhor forma de se fazer isso é assegurar que a baixa não é realizada nunca pelo NetBanking e sempre efetuada em conjunto com algumas das operações citadas acima através do uso do ERP.

**Comment by renatonlima** [comment]
Olá pessoal,

Eu analisei o PR #700 de extração do módulo de cobrança, eu vi que vocês estão implementando algumas features (como baixa do arquivo de CNAB e etc).

Hoje neste PR existe o módulo l10n_br_account_payment_cobranca, mas este módulo esta com a dependência do pycnab e pyboleto.

O ideal para a gente acelerar o trabalho destes módulos seria separar a dependência do pycnab e pyboleto em um módulo l10n_br_account_payment_cobranca_pycnab, porque com este separação e aprovação do l10n_br_account_payment_cobranca, do nosso lado podemos trabalhar no módulo l10n_br_account_payment_brcobranca (que usa a API do BRCobrança).

@mileo 

Você pode coordenar isso com o @luismalta que esta trabalhando no PR #700?

Podemos aprovar o PR #702, pois caso exista algum feature ou refatoramento, podemos fazer depois dos merges de migração.

**Comment by mileo** [comment]
Olá,

Pessoal os módulos do #700 estão em produção fazem alguns meses com certa estabilidade.

Bastante coisa foi melhorada, mas tem mais coisa para melhorar, entretanto o @hugouchoasborges que esta trabalhando no PR está de férias e só volta dia 10/1.

Eu vou revisar o #700 e repondo até o final da semana.

O @luismalta esta trabalhando na migração da folha, não creio que ele consiga ajudar ainda esta semana, mas vou ver com mais alguém do time.

Mas creio que seria viável o @mbcosta já importar os 3 commits feitos no módulo: 

https://github.com/kmee/l10n-brazil/commits/extraction/l10n_br_banking_cnab/l10n_br_account_payment_order

[]s

**Comment by renatonlima** [comment]
Pessoal,

Recentemente o @mbcosta trabalhou para limpar o módulo l10n_br_account_payment_cobranca e deixa-lo funcional, analisando um pouco melhor o módulo account_payment_order na versão 12.0 OCA/bank-payment neste módulo existem dois tipos de ordens de pagamento (outbound: para pagamentos e inbound: para recebimento) então neste caso não faz muito sentido separar/modularizar os módulos de cobrança e pagamento, também existia uma modularização para ter um módulo para imprimir o boleto e outro módulo para criar o arquivo remessa e processar o arquivo retorno, agora como só existe boletos registrados, também não faz sentido existir essa separação.

Neste caso o módulo l10n_br_account_payment_order teria a localização tanto para a cobrança quanto para os pagamentos, e abaixo dele teria as implementações, brcobrança, pycnab/pyboleto.

No PR #768 eu uni os módulo l10n_br_account_payment_order e l10n_br_account_payment_cobranca (e deixei o tavis verde) também criei um novo módulo l10n_br_account_payment_order_api para mover uma parte do código para usar a API do banco itau para emissão do boleto e limpar o módulo l10n_br_account_payment_order. Na nova arquitetura temos os seguintes módulos:

![mermaid-diagram-20200820123414](https://user-images.githubusercontent.com/211005/90794015-a8c21780-e2e2-11ea-8985-3dbd55cacebd.png)

@mileo Eu apenas movi para o modulo l10n_br_account_payment_order_api o codigo, mas o modulo nao esta instalável, eu o mantive assim porque me parece que essa feature não esta funcional, mas depois pode ser implementado.

Vocês tem alguma implementação do pyCNAB para pagamentos? caso tenha vocês podem fazer um PR podemos revisar esse trabalho e contribuir.

**Comment by mileo** [comment]
Pessoal comecei a revisar as alterações que vcs fizeram nos módulos de cobrança e pagamento. Referente a parte de pagamentos temos implementado algumas coisas sim:

- Pagamentos de tributos;
- Pagamentos de salários;
- Pagamentos TED/DOC (acabou não entrando em produção);
- API Itau;
- API INTER;

Estão neste PR: https://github.com/erpbrasil/erpbrasil.febraban/pulls

Começamos uma refatoração dos json dos cnab para simplifica-los:  Vc pode verificar no PR os três últimos commits  do @sadamo. A ideia era facilitar a manutenção da biblioteca e garantir uma interface única para geração dos arquivos. Se vocês conseguirem contribuir para finalizar isso seria ótimo.

Hoje vou trabalhar para acertar o l10n_br_pynab com essa recente alteração feita pelo Sadamo. Na sequência damos uma olhada no módulo de API para tornar-lo instável novamente e integrar com o Banco Inter.

**Comment by rvalyi** [comment]
pessoal vou fechar esse issue porque as coisas explicadas pelo @renatonlima ja foram todas implementadas.
